/* eslint-disable */
import { useState, useEffect, useRef } from "react";
import "./AIFoodFeed.css";

// ─── YOUR API KEYS ────────────────────────────────────────────────────────────
var GROQ_API_KEY       = import.meta.env.VITE_GROQ_API_KEY;
var UNSPLASH_ACCESS_KEY = import.meta.env.VITE_UNSPLASH_ACCESS_KEY; // ← paste your Unsplash Access Key

// ─── IMAGE SYSTEM ─────────────────────────────────────────────────────────────
// Uses dish.imgSearch (generated by Groq) as the Unsplash search query
// imgSearch is a generic food photography term like "paneer curry bowl"
// which Unsplash can actually find — unlike specific Indian dish names
var IMG_CACHE = {};

function fetchDishImage(cacheKey, searchTerm, callback) {
  // Return cached immediately
  if (IMG_CACHE.hasOwnProperty(cacheKey)) {
    callback(IMG_CACHE[cacheKey]);
    return;
  }

  // No Unsplash key — skip to fallback
  if (!UNSPLASH_ACCESS_KEY || UNSPLASH_ACCESS_KEY === "YOUR_UNSPLASH_ACCESS_KEY_HERE") {
    IMG_CACHE[cacheKey] = null;
    callback(null);
    return;
  }

  var q = encodeURIComponent(searchTerm || cacheKey);
  var url = "https://api.unsplash.com/search/photos"
    + "?query=" + q
    + "&per_page=1"
    + "&orientation=portrait"
    + "&content_filter=high"
    + "&client_id=" + UNSPLASH_ACCESS_KEY;

  fetch(url)
    .then(function (r) { return r.json(); })
    .then(function (d) {
      var photo = d && d.results && d.results[0];
      if (photo && photo.urls && photo.urls.raw) {
        var imgUrl = photo.urls.raw + "&w=400&h=600&fit=crop&auto=format&q=80";
        IMG_CACHE[cacheKey] = imgUrl;
        callback(imgUrl);
      } else {
        IMG_CACHE[cacheKey] = null;
        callback(null);
      }
    })
    .catch(function () {
      IMG_CACHE[cacheKey] = null;
      callback(null);
    });
}

// Fallback images — real food photos, unique per dish name (deterministic)
var FALLBACKS = [
  "https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=400&h=600&fit=crop",
  "https://images.unsplash.com/photo-1567620905732-f81944a37bdb?w=400&h=600&fit=crop",
  "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=400&h=600&fit=crop",
  "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=400&h=600&fit=crop",
  "https://images.unsplash.com/photo-1546069596-600bbec60b03?w=400&h=600&fit=crop",
  "https://images.unsplash.com/photo-1547592180-85f173990554?w=400&h=600&fit=crop",
  "https://images.unsplash.com/photo-1476224203421-9ac39bcb3327?w=400&h=600&fit=crop",
  "https://images.unsplash.com/photo-1540420773420-3366772f4999?w=400&h=600&fit=crop",
  "https://images.unsplash.com/photo-1555939594-58329b054e4f?w=400&h=600&fit=crop",
  "https://images.unsplash.com/photo-1563379926898-05f4575a45d8?w=400&h=600&fit=crop",
  "https://images.unsplash.com/photo-1482049016688-2d3e1b311543?w=400&h=600&fit=crop",
  "https://images.unsplash.com/photo-1551782045-a786e17bab20?w=400&h=600&fit=crop",
  "https://images.unsplash.com/photo-1567620832903-9fc6debc209f?w=400&h=600&fit=crop",
  "https://images.unsplash.com/photo-1574484284002-952d92456975?w=400&h=600&fit=crop",
  "https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=400&h=600&fit=crop",
  "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=400&h=600&fit=crop",
  "https://images.unsplash.com/photo-1596797038530-2c107229654b?w=400&h=600&fit=crop",
  "https://images.unsplash.com/photo-1631452180519-c014fe946bc7?w=400&h=600&fit=crop",
  "https://images.unsplash.com/photo-1606491956689-2ea866880c84?w=400&h=600&fit=crop",
  "https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=400&h=600&fit=crop",
];

// Unique fallback per dish — same dish always same fallback, no repetition
function getFallback(name) {
  var h = 0;
  for (var i = 0; i < (name || "").length; i++) {
    h += name.charCodeAt(i) * (i + 1);
  }
  return FALLBACKS[Math.abs(h) % FALLBACKS.length];
}

// ─── DishImage component ──────────────────────────────────────────────────────
function DishImage(props) {
  var dish = props.dish;
  var name = dish.name || "";
  var imgSearch = dish.imgSearch || name;
  var cls = props.className || "";

  var initSrc = IMG_CACHE.hasOwnProperty(name) && IMG_CACHE[name]
    ? IMG_CACHE[name] : getFallback(name);

  var s = useState(initSrc);
  var src = s[0]; var setSrc = s[1];
  var fetchedRef = useRef(false);

  useEffect(function () {
    if (!name) return;
    if (IMG_CACHE.hasOwnProperty(name) && IMG_CACHE[name]) { setSrc(IMG_CACHE[name]); return; }
    if (fetchedRef.current) return;
    fetchedRef.current = true;
    fetchDishImage(name, imgSearch, function (url) { if (url) setSrc(url); });
  }, [name]);

  return (
    <img src={src} alt={name} className={cls} loading="lazy"
      onError={function (e) { e.target.onerror = null; e.target.src = getFallback(name); }} />
  );
}

// ─── Groq API ─────────────────────────────────────────────────────────────────
function askGroq(sys, usr) {
  return fetch("https://api.groq.com/openai/v1/chat/completions", {
    method: "POST",
    headers: { "Content-Type": "application/json", Authorization: "Bearer " + GROQ_API_KEY },
    body: JSON.stringify({
      model: "llama-3.3-70b-versatile", max_tokens: 3000, temperature: 0.7,
      response_format: { type: "json_object" },
      messages: [{ role: "system", content: sys }, { role: "user", content: usr }],
    }),
  })
    .then(function (r) {
      if (!r.ok) return r.json().then(function (e) { throw new Error(e && e.error && e.error.message || "HTTP " + r.status); });
      return r.json();
    })
    .then(function (data) {
      var text = data.choices && data.choices[0] && data.choices[0].message && data.choices[0].message.content || "{}";
      var parsed = JSON.parse(text);
      if (Array.isArray(parsed)) return parsed;
      var key = Object.keys(parsed).find(function (k) { return Array.isArray(parsed[k]); });
      return key ? parsed[key] : [];
    });
}

// ─── Icon ─────────────────────────────────────────────────────────────────────
function Icon(props) {
  var n = (props.n || "fa-circle").replace(/fa-solid\s*/g, "").replace(/fa-regular\s*/g, "").trim();
  var parts = n.split(/\s+/).filter(Boolean);
  return <i className={["fa-solid", parts[0], parts.slice(1).join(" "), props.cls || ""].filter(Boolean).join(" ")} aria-hidden="true" />;
}

// ─── Heights ─────────────────────────────────────────────────────────────────
var HEIGHTS = [320, 420, 360, 480, 340, 400, 460, 380, 350, 430, 390, 445];

// ─── Skeleton ─────────────────────────────────────────────────────────────────
function SkeletonCard(props) {
  var h = HEIGHTS[props.index % HEIGHTS.length];
  return (
    <div className="dish-card skeleton-card" style={{ "--card-h": h + "px" }}>
      <div className="skeleton-shimmer" style={{ height: h + "px" }} />
    </div>
  );
}

// ─── Add to Plan Picker Modal ─────────────────────────────────────────────────
function AddToPlanModal(props) {
  var dish = props.dish;
  var mealPlans = props.mealPlans;
  var onConfirm = props.onConfirm;
  var onClose = props.onClose;

  var days = [];
  for (var i = 0; i < 7; i++) {
    var d = new Date();
    d.setDate(d.getDate() + i);
    var dateKey = d.toISOString().split("T")[0];
    var label = i === 0 ? "Today" : i === 1 ? "Tomorrow"
      : d.toLocaleDateString("en-US", { weekday: "short", month: "short", day: "numeric" });
    days.push({ dateKey: dateKey, label: label });
  }

  var ds = useState(days[0].dateKey);
  var selectedDate = ds[0]; var setSelectedDate = ds[1];

  var ms = useState("Breakfast");
  var selectedMeal = ms[0]; var setSelectedMeal = ms[1];

  var MEAL_TYPES = [
    { key: "Breakfast", icon: "fa-sun", color: "#f59e0b" },
    { key: "Lunch", icon: "fa-cloud-sun", color: "#10b981" },
    { key: "Dinner", icon: "fa-moon", color: "#6366f1" },
  ];

  function isSlotTaken(dateKey, mealType) {
    return mealPlans && mealPlans[dateKey] && mealPlans[dateKey][mealType] && mealPlans[dateKey][mealType].name;
  }

  function handleConfirm() { onConfirm(selectedDate, selectedMeal, dish); onClose(); }

  useEffect(function () { document.body.style.overflow = "hidden"; return function () { document.body.style.overflow = ""; }; }, []);

  return (
    <div className="atp-backdrop" onClick={onClose}>
      <div className="atp-modal" onClick={function (e) { e.stopPropagation(); }}>

        <div className="atp-header">
          <div className="atp-dish-info">
            <div className="atp-dish-img">
              <DishImage dish={dish} className="atp-dish-img-el" />
            </div>
            <div>
              <p className="atp-dish-label">Adding to plan</p>
              <h3 className="atp-dish-name">{dish.name}</h3>
              <div className="atp-dish-meta">
                <span><Icon n="fa-clock" /> {dish.time}</span>
                <span><Icon n="fa-fire" /> {dish.nutrition && dish.nutrition.calories}</span>
                <span className={"atp-veg-dot " + (dish.isVeg ? "veg" : "nonveg")}>
                  <Icon n={dish.isVeg ? "fa-leaf" : "fa-drumstick-bite"} />
                  {dish.isVeg ? "Veg" : "Non-Veg"}
                </span>
              </div>
            </div>
          </div>
          <button className="atp-close" type="button" onClick={onClose}><Icon n="fa-xmark" /></button>
        </div>

        <div className="atp-section">
          <p className="atp-section-label"><Icon n="fa-calendar" /> Choose Day</p>
          <div className="atp-day-list">
            {days.map(function (day) {
              var allTaken = MEAL_TYPES.every(function (m) { return isSlotTaken(day.dateKey, m.key); });
              return (
                <button key={day.dateKey} type="button"
                  className={"atp-day-btn " + (selectedDate === day.dateKey ? "active" : "") + (allTaken ? " full" : "")}
                  onClick={function () { setSelectedDate(day.dateKey); }}>
                  {day.label}
                  {allTaken && <span className="atp-full-tag">Full</span>}
                </button>
              );
            })}
          </div>
        </div>

        <div className="atp-section">
          <p className="atp-section-label"><Icon n="fa-utensils" /> Choose Meal Slot</p>
          <div className="atp-meal-types">
            {MEAL_TYPES.map(function (m) {
              var taken = isSlotTaken(selectedDate, m.key);
              var takenName = taken && mealPlans[selectedDate] && mealPlans[selectedDate][m.key] && mealPlans[selectedDate][m.key].name;
              return (
                <button key={m.key} type="button"
                  style={{ "--slot-color": m.color }}
                  className={"atp-meal-btn " + (selectedMeal === m.key ? "active" : "") + (taken ? " taken" : "")}
                  onClick={function () { setSelectedMeal(m.key); }}>
                  <Icon n={m.icon} cls="atp-meal-icon" />
                  <span className="atp-meal-key">{m.key}</span>
                  {taken && <span className="atp-taken-name">{takenName}</span>}
                  {!taken && <span className="atp-empty-label">Empty</span>}
                  {selectedMeal === m.key && !taken && <Icon n="fa-circle-check" cls="atp-check" />}
                </button>
              );
            })}
          </div>
          {isSlotTaken(selectedDate, selectedMeal) && (
            <p className="atp-replace-warn">
              <Icon n="fa-triangle-exclamation" /> This will replace the existing meal
            </p>
          )}
        </div>

        <div className="atp-footer">
          <button className="atp-cancel" type="button" onClick={onClose}>Cancel</button>
          <button className="atp-confirm" type="button" onClick={handleConfirm}>
            <Icon n="fa-calendar-plus" />
            Add {dish.name} to {selectedMeal}
          </button>
        </div>
      </div>
    </div>
  );
}

// ─── Dish Card ────────────────────────────────────────────────────────────────
function DishCard(props) {
  var dish = props.dish;
  var index = props.index;
  var onClick = props.onClick;
  var onAddPlan = props.onAddPlan;
  var h = HEIGHTS[index % HEIGHTS.length];

  function handleAddClick(e) {
    e.stopPropagation();
    onAddPlan(dish);
  }

  return (
    <div className="dish-card" style={{ "--card-h": h + "px", animationDelay: (index * 0.06) + "s" }}
      onClick={function () { onClick(dish); }}>
      <div className="dish-card-img-wrap">
        <DishImage dish={dish} className="dish-card-img" />
        <div className="dish-card-overlay" />
      </div>

      <div className="dish-card-top">
        <span className={"dish-badge sm " + (dish.isVeg ? "veg" : "nonveg")}>
          <Icon n={dish.isVeg ? "fa-leaf" : "fa-drumstick-bite"} />
          {dish.isVeg ? "Veg" : "Non-Veg"}
        </span>
      </div>

      <button type="button" className="card-add-btn" onClick={handleAddClick} title="Add to Meal Plan">
        <Icon n="fa-plus" />
      </button>

      <div className="dish-card-bottom">
        <span className="dish-card-cuisine">{dish.cuisine}</span>
        <h3 className="dish-card-name">{dish.name}</h3>
        <div className="dish-card-meta">
          <span><Icon n="fa-clock" /> {dish.time}</span>
          <span><Icon n="fa-signal" /> {dish.difficulty}</span>
          {dish.nutrition && dish.nutrition.calories && <span><Icon n="fa-fire" /> {dish.nutrition.calories}</span>}
        </div>
        <button type="button" className="card-add-row" onClick={handleAddClick}>
          <Icon n="fa-calendar-plus" /> Add to Meal Plan
        </button>
      </div>
    </div>
  );
}

// ─── Dish Modal ───────────────────────────────────────────────────────────────
function DishModal(props) {
  var dish = props.dish;
  var onClose = props.onClose;
  var onAddPlan = props.onAddPlan;

  useEffect(function () {
    document.body.style.overflow = "hidden";
    return function () { document.body.style.overflow = ""; };
  }, []);

  if (!dish) return null;
  var nutr = dish.nutrition || {};

  return (
    <div className="modal-backdrop" onClick={onClose}>
      <div className="modal-sheet" onClick={function (e) { e.stopPropagation(); }}>
        <button className="modal-close" type="button" onClick={onClose}><Icon n="fa-xmark" /></button>

        <div className="modal-img-wrap">
          <DishImage dish={dish} className="modal-img" />
          <div className="modal-img-overlay" />
          <div className="modal-img-badges">
            <span className={"dish-badge " + (dish.isVeg ? "veg" : "nonveg")}>
              <Icon n={dish.isVeg ? "fa-leaf" : "fa-drumstick-bite"} />
              {dish.isVeg ? "Vegetarian" : "Non-Veg"}
            </span>
            <span className="dish-badge time"><Icon n="fa-clock" /> {dish.time}</span>
            <span className="dish-badge diff"><Icon n="fa-signal" /> {dish.difficulty}</span>
          </div>
        </div>

        <div className="modal-body">
          <div className="modal-cuisine-tag">{dish.cuisine}</div>
          <h2 className="modal-title">{dish.name}</h2>
          <p className="modal-desc">{dish.description}</p>

          <div className="modal-nutrition">
            {[
              { icon: "fa-fire", label: "Calories", val: nutr.calories },
              { icon: "fa-dumbbell", label: "Protein", val: nutr.protein },
              { icon: "fa-wheat-awn", label: "Carbs", val: nutr.carbs },
              { icon: "fa-droplet", label: "Fat", val: nutr.fat },
            ].map(function (r) {
              return (
                <div className="nutr-item" key={r.label}>
                  <Icon n={r.icon} cls="nutr-icon" />
                  <span className="nutr-val">{r.val || "—"}</span>
                  <span className="nutr-label">{r.label}</span>
                </div>
              );
            })}
          </div>

          {dish.ingredients && dish.ingredients.length > 0 && (
            <div className="modal-section">
              <h3 className="modal-section-title"><Icon n="fa-list-ul" /> Ingredients</h3>
              <div className="ingredients-wrap">
                {dish.ingredients.map(function (ing, i) { return <span className="ingredient-chip" key={i}>{ing}</span>; })}
              </div>
            </div>
          )}

          {dish.steps && dish.steps.length > 0 && (
            <div className="modal-section">
              <h3 className="modal-section-title"><Icon n="fa-list-ol" /> How to Cook</h3>
              <ol className="steps-list">
                {dish.steps.map(function (step, i) {
                  return (
                    <li className="step-item" key={i}>
                      <span className="step-num">{i + 1}</span>
                      <span className="step-text">{step}</span>
                    </li>
                  );
                })}
              </ol>
            </div>
          )}

          <div className="modal-actions">
            <button className="btn-add-plan" type="button" onClick={function () { onAddPlan(dish); onClose(); }}>
              <Icon n="fa-calendar-plus" /> Add to Meal Plan
            </button>
            <button className="btn-save" type="button"><Icon n="fa-bookmark" /></button>
          </div>
        </div>
      </div>
    </div>
  );
}

// ─── Mic Button ───────────────────────────────────────────────────────────────
function MicButton(props) {
  return (
    <div className="mic-container">
      {props.transcript && (
        <div className="mic-transcript"><Icon n="fa-quote-left" cls="transcript-quote" />{props.transcript}</div>
      )}
      <button type="button" className={"mic-btn " + (props.listening ? "listening" : "")} onClick={props.onClick}>
        {props.listening && <span><div className="mic-ring r1" /><div className="mic-ring r2" /><div className="mic-ring r3" /></span>}
        <Icon n={props.listening ? "fa-stop" : "fa-microphone"} cls="mic-icon" />
      </button>
      <div className="mic-label">{props.listening ? "Listening..." : "Tap to speak"}</div>
    </div>
  );
}

// ─── Success Toast ────────────────────────────────────────────────────────────
function Toast(props) {
  useEffect(function () {
    var t = setTimeout(props.onHide, 3000);
    return function () { clearTimeout(t); };
  }, []);
  return (
    <div className="atp-toast">
      <Icon n="fa-circle-check" cls="toast-icon" />
      <span>{props.message}</span>
    </div>
  );
}

// ─── Main Feed ────────────────────────────────────────────────────────────────
export default function AIFoodFeed(props) {
  console.log("GROQ KEY:", import.meta.env.VITE_GROQ_API_KEY); // ← add this
  // ... rest of your code
  var addMeal = props.addMeal;
  var mealPlans = props.mealPlans || {};

  var prefs = {};
  try { prefs = JSON.parse(localStorage.getItem("kitchenBuddyPrefs") || "{}"); } catch (e) { }

  var s1 = useState([]); var dishes = s1[0]; var setDishes = s1[1];
  var s2 = useState(false); var loading = s2[0]; var setLoading = s2[1];
  var s3 = useState(""); var errMsg = s3[0]; var setErrMsg = s3[1];
  var s4 = useState(null); var selected = s4[0]; var setSelected = s4[1];
  var s5 = useState(false); var listening = s5[0]; var setListening = s5[1];
  var s6 = useState(""); var transcript = s6[0]; var setTranscript = s6[1];
  var s7 = useState(""); var query = s7[0]; var setQuery = s7[1];
  var s8 = useState("all"); var filter = s8[0]; var setFilter = s8[1];
  var s9 = useState(null); var planDish = s9[0]; var setPlanDish = s9[1];
  var s10 = useState(""); var toast = s10[0]; var setToast = s10[1];

  var recRef = useRef(null);
  var inputRef = useRef(null);

  function getVal(v) {
    if (!v) return "";
    if (Array.isArray(v)) return v.map(function (x) { return x.label || x; }).join(", ");
    return v.label || v;
  }

  function buildCtx() {
    var lines = [];
    if (prefs.name) lines.push("Name: " + prefs.name);
    if (prefs.country) lines.push("Country: " + getVal(prefs.country));
    if (prefs.region) lines.push("Region: " + getVal(prefs.region));
    if (prefs.diet) lines.push("Diet: " + getVal(prefs.diet));
    if (prefs.spice) lines.push("Spice: " + getVal(prefs.spice));
    if (prefs.cuisines) lines.push("Cuisines: " + getVal(prefs.cuisines));
    if (prefs.skill) lines.push("Skill: " + getVal(prefs.skill));
    if (prefs.cookTime) lines.push("Cook time: " + getVal(prefs.cookTime));
    if (prefs.dislikes && prefs.dislikes.length) lines.push("Dislikes: " + getVal(prefs.dislikes));
    if (prefs.allergies && prefs.allergies.length) lines.push("Allergies: " + getVal(prefs.allergies));
    return lines.join("\n");
  }

  function fetchDishes(userQuery) {
    if (userQuery === undefined) userQuery = "";
    setLoading(true); setErrMsg(""); setDishes([]);
    var sys = [
      "You are Kitchen Buddy's AI chef. Respond ONLY as JSON: {\"dishes\": [...]}",
      "Each dish needs: id, name, cuisine, description (2 sentences), time, difficulty (Easy/Medium/Hard),",
      "isVeg (boolean true or false — must have BOTH veg and non-veg dishes),",
      "nutrition ({calories,protein,carbs,fat} as strings), ingredients (6-8), steps (4-6), tags (2-3),",
      "imgSearch (2-3 word English food photography term for Unsplash.",
      "Examples: 'paneer curry bowl', 'grilled chicken plate', 'biryani rice pot', 'salmon fillet herbs'.",
      "NEVER use dish name — use descriptive food photography terms.)",
      "IMPORTANT: Always include a mix of both vegetarian AND non-vegetarian dishes regardless of user diet.",
      "The user will filter themselves. Aim for roughly 50% veg and 50% non-veg in every response."
    ].join("\n");
    var ctx = buildCtx() || "General food lover";
    var usr = userQuery
      ? "User profile:\n" + ctx + "\n\nRequest: \"" + userQuery + "\"\nReturn {\"dishes\":[12 dishes mixing veg and non-veg]}"
      : "User profile:\n" + ctx + "\n\nSuggest 12 dishes for today. Mix breakfast, lunch, snacks, dinner.\nInclude 6 vegetarian AND 6 non-vegetarian dishes.\nReturn {\"dishes\":[12 dishes]}";
    askGroq(sys, usr)
      .then(function (r) {
        if (!Array.isArray(r) || r.length === 0) { setErrMsg("No dishes returned. Try refreshing."); }
        else { setDishes(r.slice(0, 12)); }
        setLoading(false);
      })
      .catch(function (e) { setErrMsg("AI error: " + e.message); setLoading(false); });
  }

  useEffect(function () { fetchDishes(""); }, []);

  function handleConfirmAdd(dateKey, mealType, dish) {
    var meal = {
      name: dish.name, time: dish.time,
      calories: dish.nutrition && dish.nutrition.calories,
      cuisine: dish.cuisine, description: dish.description,
      ingredients: dish.ingredients, steps: dish.steps,
      isVeg: dish.isVeg, difficulty: dish.difficulty, source: "ai_feed",
    };
    addMeal(dateKey, mealType, meal);
    var d = new Date(dateKey + "T00:00:00");
    var isToday = dateKey === new Date().toISOString().split("T")[0];
    var dayLabel = isToday ? "Today" : d.toLocaleDateString("en-US", { weekday: "long" });
    setToast(dish.name + " added to " + mealType + " on " + dayLabel + "!");
  }

  function startListening() {
    var SR = window.SpeechRecognition || window.webkitSpeechRecognition;
    if (!SR) { alert("Voice input needs Chrome."); return; }
    var rec = new SR();
    rec.lang = "en-US"; rec.interimResults = true;
    rec.onstart = function () { setListening(true); };
    rec.onend = function () { setListening(false); };
    rec.onerror = function () { setListening(false); };
    rec.onresult = function (e) {
      var t = Array.from(e.results).map(function (r) { return r[0].transcript; }).join("");
      setTranscript(t);
      if (e.results[e.results.length - 1].isFinal) {
        setQuery(t); fetchDishes(t);
        setTimeout(function () { setTranscript(""); }, 3000);
      }
    };
    rec.start(); recRef.current = rec;
  }

  function stopListening() { if (recRef.current) recRef.current.stop(); setListening(false); }

  var filtered = dishes.filter(function (d) {
    if (filter === "veg") return d.isVeg === true;
    if (filter === "nonveg") return d.isVeg === false;
    return true;
  });

  var SUGGESTIONS = ["Something quick for breakfast", "High protein lunch", "Comfort food dinner", "Healthy and light", "Street food vibes", "Something spicy"];
  var FILTERS = [
    { key: "all", label: "All Dishes", icon: "fa-utensils" },
    { key: "veg", label: "Vegetarian", icon: "fa-leaf" },
    { key: "nonveg", label: "Non-Veg", icon: "fa-drumstick-bite" },
  ];

  return (
    <div className="feed-root">

      <div className="feed-hero">
        <div className="feed-hero-inner">
          <h1 className="feed-hero-title">What should I cook<span className="feed-hero-accent"> today?</span></h1>
          <p className="feed-hero-sub">Speak or type — AI finds dishes personalised just for you</p>
          <form className="feed-search-bar" onSubmit={function (e) { e.preventDefault(); if (query.trim()) fetchDishes(query.trim()); }}>
            <Icon n="fa-magnifying-glass" cls="search-icon" />
            <input ref={inputRef} className="feed-search-input"
              placeholder="Try paneer butter masala or quick breakfast..."
              value={query} onChange={function (e) { setQuery(e.target.value); }} />
            {query && <button type="button" className="search-clear" onClick={function () { setQuery(""); }}><Icon n="fa-xmark" /></button>}
            <button type="submit" className="search-submit"><Icon n="fa-arrow-right" /></button>
          </form>
          <div className="suggestion-chips">
            {SUGGESTIONS.map(function (s) {
              return <button key={s} type="button" className="suggestion-chip" onClick={function () { setQuery(s); fetchDishes(s); }}>{s}</button>;
            })}
          </div>
        </div>
      </div>

      <div className="feed-filter-bar">
        <div className="feed-filter-inner">
          <div className="filter-tabs">
            {FILTERS.map(function (opt) {
              return (
                <button key={opt.key} type="button"
                  className={"filter-tab " + (filter === opt.key ? "active" : "")}
                  onClick={function () { setFilter(opt.key); }}>
                  <Icon n={opt.icon} /> {opt.label}
                </button>
              );
            })}
          </div>
          <button type="button" className="refresh-btn" onClick={function () { fetchDishes(query); }} disabled={loading}>
            <Icon n={loading ? "fa-circle-notch fa-spin" : "fa-rotate"} />
            {loading ? "Loading..." : "Refresh Feed"}
          </button>
        </div>
      </div>

      {errMsg && !loading && (
        <div className="feed-error-banner">
          <Icon n="fa-circle-exclamation" /><span>{errMsg}</span>
          <button type="button" onClick={function () { fetchDishes(query); }}><Icon n="fa-rotate" /> Retry</button>
        </div>
      )}

      <div className="feed-grid-wrap">
        <div className="masonry-grid">
          {loading
            ? Array.from({ length: 12 }).map(function (_, i) { return <SkeletonCard key={i} index={i} />; })
            : filtered.length === 0 && !errMsg
              ? (
                <div className="feed-empty">
                  <Icon n="fa-face-sad-tear" cls="empty-icon" />
                  <p>No dishes found.</p>
                  <button type="button" onClick={function () { setFilter("all"); fetchDishes(""); }}><Icon n="fa-rotate" /> Reset</button>
                </div>
              )
              : filtered.map(function (dish, i) {
                return <DishCard key={dish.id || i} dish={dish} index={i} onClick={setSelected} onAddPlan={setPlanDish} />;
              })
          }
        </div>
      </div>

      <MicButton listening={listening} transcript={transcript}
        onClick={function () { if (listening) stopListening(); else startListening(); }} />

      {selected && (
        <DishModal dish={selected} onClose={function () { setSelected(null); }}
          onAddPlan={function (d) { setSelected(null); setPlanDish(d); }} />
      )}

      {planDish && (
        <AddToPlanModal dish={planDish} mealPlans={mealPlans}
          onConfirm={handleConfirmAdd} onClose={function () { setPlanDish(null); }} />
      )}

      {toast && <Toast message={toast} onHide={function () { setToast(""); }} />}

    </div>
  );
}